<p style ="text-align:center">
    <img src="http://epecora.com.br/DataFiles/BannerUFPR.png" width="700" alt="PPGOLD/PPGMNE Python:INTRO"  />
</p>


# SAOP09 - Data Science For Business
## Prof. Eduardo Pécora

# Pré-tratamento dos dados
Tempo estimado: **60** minutos

## Objetivos

Após completar esta aula, você será capaz de:

* Identificar os dados faltantes no DF
* Tratar dados faltantes, deletando ou subtituindo-os

In [1]:
# import libraries
import pandas as pd  # Biblioteca para os DataFrames 
import numpy as np   # Biblioteca Numérica

# Ler o arquivo, e atribua-o à variável "df".
my_file = "https://raw.githubusercontent.com/EduPekUfpr/PythonProject/refs/heads/main/Dados/Auto_limpo.csv"

# Atribuir o arquivo a uma váriável DataFrame
df = pd.read_csv( my_file)

df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,164.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

## Valores Faltantes (Missing Data)

A primeira pergunta a ser feita é quantos dados estão faltando?

### Forma 1:

Para isso vamos criar um DataFrame chamado `missing_data` onde:

* "True" signifca que o valor é faltante 
* "False" signifca que o valor é presente

In [2]:
missing_data = df.isna()
missing_data.head(5)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

<h3>Contar valores ausentes em cada coluna</h3>
<p>
Usando um loop em Python, podemos descobrir rapidamente o número de valores em falta em cada coluna. Como mencionado acima, "True" representa um valor ausente e "False" significa que o valor está presente no conjunto de dados.  

No corpo do loop `for` , o método ".value_counts()" conta o número de valores "True" e "False". 
</p>

In [3]:
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("\n")

symboling
symboling
False    205
Name: count, dtype: int64


normalized-losses
normalized-losses
False    165
True      40
Name: count, dtype: int64


make
make
False    205
Name: count, dtype: int64


fuel-type
fuel-type
False    205
Name: count, dtype: int64


aspiration
aspiration
False    205
Name: count, dtype: int64


num-of-doors
num-of-doors
False    203
True       2
Name: count, dtype: int64


body-style
body-style
False    205
Name: count, dtype: int64


drive-wheels
drive-wheels
False    205
Name: count, dtype: int64


engine-location
engine-location
False    205
Name: count, dtype: int64


wheel-base
wheel-base
False    205
Name: count, dtype: int64


length
length
False    205
Name: count, dtype: int64


width
width
False    205
Name: count, dtype: int64


height
height
False    205
Name: count, dtype: int64


curb-weight
curb-weight
False    205
Name: count, dtype: int64


engine-type
engine-type
False    205
Name: count, dtype: int64


num-of-cylinders
num-of-cylinders
False    205
Name: count, dtype: int64


engine-size
engine-size
False    205
Name: count, dtype: int64


fuel-system
fuel-system
False    205
Name: count, dtype: int64


bore
bore
False    201
True       4
Name: count, dtype: int64


stroke
stroke
False    201
True       4
Name: count, dtype: int64


compression-ratio
compression-ratio
False    205
Name: count, dtype: int64


horsepower
horsepower
False    203
True       2
Name: count, dtype: int64


peak-rpm
peak-rpm
False    203
True       2
Name: count, dtype: int64


city-mpg
city-mpg
False    205
Name: count, dtype: int64


highway-mpg
highway-mpg
False    205
Name: count, dtype: int64


price
price
False    201
True       4
Name: count, dtype: int64

### Uma segunda forma mais simplificada de contar os valores faltantes nas colunas

In [4]:
for column in df.columns.values.tolist():
  total = df[column].isna().sum()
  if total > 1:
    print(column, "\t NaN = ",total)

normalized-losses 	 NaN =  40
num-of-doors 	 NaN =  2
bore 	 NaN =  4
stroke 	 NaN =  4
horsepower 	 NaN =  2
peak-rpm 	 NaN =  2
price 	 NaN =  4

### Outra forma mais simples ainda

In [5]:
df.isna().sum() # missing_data.sum()

symboling             0
normalized-losses    40
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

### Valores faltantes por linha

* ```df.loc[[i]]```: seleciona a linha de índice i do DataFrame, retornando-a como um DataFrame (não uma Série, por isso o uso de ```[[i]])```.
* ```.isna()```: verifica se há valores faltantes (NA) na linha, retornando uma máscara booleana onde True indica NaN.
* ```.sum()```: a primeira soma conta os valores True (indicando NA) para cada coluna da linha, resultando em uma Série com o total de NaN por coluna.
* A segunda ```.sum()``` soma os valores dessa Série, dando o número total de NaN em toda a linha.

In [6]:
for i in range(df.shape[0]):
  total = df.loc[[i]].isna().sum().sum()
  if total >= 1:
    print("Linha ", i, "\t NaN = ",total)

Linha  0 	 NaN =  1
Linha  1 	 NaN =  1
Linha  5 	 NaN =  1
Linha  7 	 NaN =  1
Linha  9 	 NaN =  2
Linha  14 	 NaN =  1
Linha  15 	 NaN =  1
Linha  16 	 NaN =  1
Linha  17 	 NaN =  1
Linha  27 	 NaN =  1
Linha  43 	 NaN =  1
Linha  44 	 NaN =  2
Linha  45 	 NaN =  2
Linha  46 	 NaN =  1
Linha  48 	 NaN =  1
Linha  49 	 NaN =  1
Linha  55 	 NaN =  2
Linha  56 	 NaN =  2
Linha  57 	 NaN =  2
Linha  58 	 NaN =  2
Linha  63 	 NaN =  2
Linha  66 	 NaN =  1
Linha  71 	 NaN =  1
Linha  73 	 NaN =  1
Linha  74 	 NaN =  1
Linha  75 	 NaN =  1
Linha  82 	 NaN =  1
Linha  83 	 NaN =  1
Linha  84 	 NaN =  1
Linha  109 	 NaN =  1
Linha  110 	 NaN =  1
Linha  113 	 NaN =  1
Linha  114 	 NaN =  1
Linha  124 	 NaN =  1
Linha  126 	 NaN =  1
Linha  127 	 NaN =  1
Linha  128 	 NaN =  1
Linha  129 	 NaN =  2
Linha  130 	 NaN =  3
Linha  131 	 NaN =  3
Linha  181 	 NaN =  1
Linha  189 	 NaN =  1
Linha  191 	 NaN =  1
Linha  192 	 NaN =  1
Linha  193 	 NaN =  1

### Outra forma

In [7]:
df.loc[df.isna().sum(axis=1)>=1]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,15250.0
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,18920.0
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160.0,5500.0,16,22,NaN
14,1,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121.0,4250.0,20,25,24565.0
15,0,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182.0,5400.0,16,22,30760.0
16,0,NaN,bmw,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182.0,5400.0,16,22,41315.0
17,0,NaN,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.0,182.0,5400.0,15,20,36880.0
27,1,148.0,dodge,gas,turbo,NaN,sedan,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.6,102.0,5500.0,24,30,8558.0
43,0,NaN,isuzu,gas,std,four,sedan,rwd,front,94.3,...,111,2bbl,3.31,3.23,8.5,78.0,4800.0,24,29,6785.0
44,1,NaN,isuzu,gas,std,two,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70.0,5400.0,38,43,NaN
45,0,NaN,isuzu,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70.0,5400.0,38,43,NaN
46,2,NaN,isuzu,gas,std,two,hatchback,rwd,front,96.0,...,119,spfi,3.43,3.23,9.2,90.0,5000.0,24,29,11048.0
48,0,NaN,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.1,176.0,4750.0,15,19,35550.0
49,0,NaN,jaguar,gas,std,two,sedan,rwd,front,102.0,...,326,mpfi,3.54,2.76,11.5,262.0,5000.0,13,17,36000.0
55,3,150.0,mazda,gas,std,two,hatchback,rwd,front,95.3,...,70,4bbl,NaN,NaN,9.4,101.0,6000.0,17,23,10945.0
56,3,150.0,mazda,gas,std,two,hatchback,rwd,front,95.3,...,70,4bbl,NaN,NaN,9.4,101.0,6000.0,17,23,11845.0
57,3,150.0,mazda,gas,std,two,hatchback,rwd,front,95.3,...,70,4bbl,NaN,NaN,9.4,101.0,6000.0,17,23,13645.0
58,3,150.0,mazda,gas,std,two,hatchback,rwd,front,95.3,...,80,mpfi,NaN,NaN,9.4,135.0,6000.0,16,23,15645.0
63,0,NaN,mazda,diesel,std,NaN,sedan,fwd,front,98.8,...,122,idi,3.39,3.39,22.7,64.0,4650.0,36,42,10795.0
66,0,NaN,mazda,diesel,std,four,sedan,rwd,front,104.9,...,134,idi,3.43,3.64,22.0,72.0,4200.0,31,39,18344.0
71,-1,NaN,mercedes-benz,gas,std,four,sedan,rwd,front,115.6,...,234,mpfi,3.46,3.10,8.3,155.0,4750.0,16,18,34184.0
73,0,NaN,mercedes-benz,gas,std,four,sedan,rwd,front,120.9,...,308,mpfi,3.80,3.35,8.0,184.0,4500.0,14,16,40960.0
74,1,NaN,mercedes-benz,gas,std,two,hardtop,rwd,front,112.0,...,304,mpfi,3.80,3.35,8.0,184.0,4500.0,14,16,45400.0
75,1,NaN,mercury,gas,turbo,two,hatchback,rwd,front,102.7,...,140,mpfi,3.78,3.12,8.0,175.0,5000.0,19,24,16503.0
82,3,NaN,mitsubishi,gas,turbo,two,hatchback,fwd,front,95.9,...,156,spdi,3.58,3.86,7.0,145.0,5000.0,19,24,12629.0
83,3,NaN,mitsubishi,gas,turbo,two,hatchback,fwd,front,95.9,...,156,spdi,3.59,3.86,7.0,145.0,5000.0,19,24,14869.0
84,3,NaN,mitsubishi,gas,turbo,two,hatchback,fwd,front,95.9,...,156,spdi,3.59,3.86,7.0,145.0,5000.0,19,24,14489.0
109,0,NaN,peugot,gas,std,four,wagon,rwd,front,114.2,...,120,mpfi,3.46,3.19,8.4,97.0,5000.0,19,24,12440.0
110,0,NaN,peugot,diesel,turbo,four,wagon,rwd,front,114.2,...,152,idi,3.70,3.52,21.0,95.0,4150.0,25,25,13860.0
113,0,NaN,peugot,gas,std,four,wagon,rwd,front,114.2,...,120,mpfi,3.46,2.19,8.4,95.0,5000.0,19,24,16695.0
114,0,NaN,peugot,diesel,turbo,four,wagon,rwd,front,114.2,...,152,idi,3.70,3.52,21.0,95.0,4150.0,25,25,17075.0
124,3,NaN,plymouth,gas,turbo,two,hatchback,rwd,front,95.9,...,156,spdi,3.59,3.86,7.0,145.0,5000.0,19,24,12764.0
126,3,NaN,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,194,mpfi,3.74,2.90,9.5,207.0,5900.0,17,25,32528.0
127,3,NaN,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,194,mpfi,3.74,2.90,9.5,207.0,5900.0,17,25,34028.0
128,3,NaN,porsche,gas,std,two,convertible,rwd,rear,89.5,...,194,mpfi,3.74,2.90,9.5,207.0,5900.0,17,25,37028.0
129,1,NaN,porsche,gas,std,two,hatchback,rwd,front,98.4,...,203,mpfi,3.94,3.11,10.0,288.0,5750.0,17,28,NaN
130,0,NaN,renault,gas,std,four,wagon,fwd,front,96.1,...,132,mpfi,3.46,3.90,8.7,NaN,NaN,23,31,9295.0
131,2,NaN,renault,gas,std,two,hatchback,fwd,front,96.1,...,132,mpfi,3.46,3.90,8.7,NaN,NaN,23,31,9895.0
181,-1,NaN,toyota,gas,std,four,wagon,rwd,front,104.5,...,161,mpfi,3.27,3.35,9.2,156.0,5200.0,19,24,15750.0
189,3,NaN,volkswagen,gas,std,two,convertible,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.5,90.0,5500.0,24,29,11595.0
191,0,NaN,volkswagen,gas,std,four,sedan,fwd,front,100.4,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,24,13295.0
192,0,NaN,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.40,23.0,68.0,4500.0,33,38,13845.0
193,0,NaN,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.40,9.0,88.0,5500.0,25,31,12290.0

#  Quais são as opções para lidar com dados ausentes?


## Deletar os Dados
  * Deletar a linha inteira
  * Deletar a coluna inteira

As colunas inteiras só devem ser descartadas se a maioria dos dados da coluna estiver vazia. Em nosso conjunto de dados, nenhuma das colunas está vazia o suficiente para ser descartada completamente.

Quando temos uma linha com muitos dados faltantes, levanta-se a hipótese da veracidade dela. Portanto também podemos deletá-la.

-----
**Deletar a linha inteira:**

* "preço": 4 dados em falta, basta apagar a linha inteira

Razão: o preço é o que queremos prever. Qualquer entrada de dados sem dados de preço não pode ser usada para previsão; portanto, qualquer linha sem dados de preço não nos é útil.

-----

In [8]:
# Delete a linha toda com NaN na coluna "price" 
df.dropna(subset=["price"], axis=0, inplace = True)

#df = df.dropna(subset=["price"], axis=0)

# reset index, because we droped some rows
df.reset_index(drop = True, inplace = True)

df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,164.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

## Substituir dados
* Substituir pela média
* Substituir pela maior frequência
* Substituir com base em outras funções

Temos alguma liberdade para escolher qual método substituir os dados; no entanto, alguns métodos podem parecer mais razoáveis do que outros. 

**Substituir pela média:**

* "normalized-losses": 41 dados faltantes, substitua-os pela média
*"stroke": 4 dados faltantes, substitua-os pela média
* "bore": 4 dados faltantes, substitua-os pela média<
*"horse-power": 2 dados faltantes, substitua-os pela média
*"peak-rpm": 2 dados faltantes, substitua-os pela média

In [9]:
# Cálculo da média normalized-losses
avg_norm_loss = df["normalized-losses"].astype("float").mean(axis=0)
print("Average of normalized-losses:", avg_norm_loss)

# Substituição pela média normalized-losses
df["normalized-losses"] = df["normalized-losses"].fillna(avg_norm_loss)

Average of normalized-losses: 122.25454545454545

In [10]:
# bore
avg_bore= df["bore"].astype("float").mean(axis=0)
print("Average of bore:", avg_bore)
df["bore"] = df["bore"].fillna(avg_bore) 

# stroke
avg_stroke=df['stroke'].astype('float').mean(axis=0)
print("Average stroke:", avg_stroke)
df['stroke'] = df['stroke'].fillna(avg_stroke)

# horsepower
avg_horsepower = df['horsepower'].astype('float').mean(axis=0)
print("Average horsepower:", avg_horsepower)
df['horsepower'] = df['horsepower'].fillna(avg_horsepower)

# peak-rpm
avg_peakrpm=df['peak-rpm'].astype('float').mean(axis=0)
print("Average peak rpm:", avg_peakrpm)
df['peak-rpm'] = df['peak-rpm'].fillna(avg_peakrpm)

Average of bore: 3.330710659898477
Average stroke: 3.256903553299492
Average horsepower: 103.39698492462311
Average peak rpm: 5117.587939698493

# Categorical Data

## Valor mais frequente (Dados Categóricos)

**Substituir pela frequência:**

* "num-of-doors": 2 dados faltantes, substitua-os pelo valor mais frequente.

Razão: 84% de sedans são quatro portas. Como quatro portas é a mais frequente, é mais provável que ocorra

In [11]:
# Valor mais frequente de num-of-doors
print(df['num-of-doors'].value_counts()) # imprime a contagem de cada valor

a = df['num-of-doors'].mode() # mode pega valor mais frequente

print("Valor mais frequente de num-of-doors: ", a)

#Substitua o valor 'num-of-doors' pelo mais frequente
df["num-of-doors"] = df["num-of-doors"].fillna(a[0])

num-of-doors
four    113
two      86
Name: count, dtype: int64
Valor mais frequente de num-of-doors:  0    four
Name: num-of-doors, dtype: object

### Dá pra fazer melhor ?

SEMPRE !

#FicaADica

In [12]:
df.groupby(['num-of-doors', "body-style"]).size()

num-of-doors  body-style
four          hatchback      10
              sedan          80
              wagon          25
two           convertible     6
              hardtop         8
              hatchback      58
              sedan          14
dtype: int64

## Desafio 

Como você subtituiria as portas considerando o tipo de carroceria?

## Devemos Conferir tudo

In [13]:
missing_data = df.isnull()
missing_data.head(5)

for column in df.columns.values.tolist():
  total = df[column].isna().sum()
  if (total > 1):
    print(column, "\t NaN = ",total)

## Exporte o seu novo DataFrame

In [14]:
path = "Auto_pronto.csv"

df.to_csv(path, index = False)

## Fique Conectado

- [![YouTube](https://img.icons8.com/ios-filled/40/000000/youtube-play.png)](https://www.youtube.com/@LigaDataScience/videos)  
  Explore nossos vídeos educacionais e webinars sobre ciência de dados, machine learning e inteligência artificial. Inscreva-se para não perder nenhuma atualização!

- [![LinkedIn](https://img.icons8.com/ios-filled/40/000000/linkedin.png)](https://www.linkedin.com/company/liga-data-science-ufpr/)  
  Siga-nos no LinkedIn para as últimas novidades, oportunidades de carreira e networking profissional no campo da ciência de dados.

- [![Instagram](https://img.icons8.com/ios-filled/40/000000/instagram-new.png)](https://www.instagram.com/ligadatascience/)  
  Confira nosso Instagram para conteúdos dos bastidores, destaques de eventos e o dia a dia da Liga Data Science. Faça parte da nossa jornada!

## Autores

<a href="https://www.linkedin.com/in/eduardopecora/" target="_blank">Eduardo Pecora</a>,

## Referências:

Traduzido e inspirado do material desenvolvido pela IBM:
<a href="https://www.linkedin.com/in/joseph-s-50398b136/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDA0101ENSkillsNetwork20235326-2021-01-01" target="_blank">Joseph Santarcangelo</a>

* Documentação da biblioteca <a href="https://pandas.pydata.org/docs/">Pandas</a>

## Log de modificações

|  Date (YYYY-MM-DD) |  Version | Changed By  |  Change Description |
|---|---|---|---|
| 2020-10-06  | 0.9  | <a href="https://www.linkedin.com/in/eduardopecora/" target="_blank">Eduardo Pécora</a> |  Initial development |
| 2021-03-12  | 1.0  | <a href="https://www.linkedin.com/in/eduardopecora/" target="_blank">Eduardo Pécora</a> |  Categorical Data |
| 2024-10-17  | 1.1  | <a href="https://www.linkedin.com/in/eduardopecora/" target="_blank">Eduardo Pécora</a> |  Estrutura de Aula |